builds:
- main: ./cmd/sshscan/sshscan_main.go
  env:
    - CGO_ENABLED=0
  goos: 
    - darwin
  goarch:
    - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brew:
  github:
    owner: adedayo
    name: homebrew-tap
  homepage: "https://github.com/adedayo/sshscan"
  description: "SSHScan is a simple utility for inspecting SSH key exchange settings on SSH servers"
